#!/bin/bash

TOP_VIDEO=$1
BOTTOM_VIDEO=$2
OUTPUT_VIDEO=$3

CURRENT_DIR="$(pwd)"
ABSOLUTE_TOP_VIDEO=$(realpath "${TOP_VIDEO}")
ABSOLUTE_BOTTOM_VIDEO=$(realpath "${BOTTOM_VIDEO}")
ABSOLUTE_OUTPUT_VIDEO=$(realpath "${OUTPUT_VIDEO}")


ffmpeg -i ${ABSOLUTE_TOP_VIDEO} -i ${ABSOLUTE_BOTTOM_VIDEO} -filter_complex '[1][0]scale2ref=iw:ow/mdar[2nd][ref];[ref][2nd]vstack[vid]' -map [vid] -c:v libx264 -crf 23 -preset veryfast ${ABSOLUTE_OUTPUT_VIDEO}
